/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SvgClock {
    /**
    * Automatically start the clock.
    */
    'autoplay': boolean;
    /**
    * The interval to check the time. Decrease for smoother animation and increased performance cost.
    */
    'interval': number;
    'isRunning': () => Promise<boolean>;
    'start': () => Promise<void>;
    'stop': () => Promise<void>;
    /**
    * The center of the hands used in the SVG `transform` attribute. Required for supporting IE11 and Edge <17.
    */
    'svgRotationOrigin': string;
  }
}

declare global {


  interface HTMLSvgClockElement extends Components.SvgClock, HTMLStencilElement {}
  var HTMLSvgClockElement: {
    prototype: HTMLSvgClockElement;
    new (): HTMLSvgClockElement;
  };
  interface HTMLElementTagNameMap {
    'svg-clock': HTMLSvgClockElement;
  }
}

declare namespace LocalJSX {
  interface SvgClock extends JSXBase.HTMLAttributes<HTMLSvgClockElement> {
    /**
    * Automatically start the clock.
    */
    'autoplay'?: boolean;
    /**
    * The interval to check the time. Decrease for smoother animation and increased performance cost.
    */
    'interval'?: number;
    /**
    * The center of the hands used in the SVG `transform` attribute. Required for supporting IE11 and Edge <17.
    */
    'svgRotationOrigin'?: string;
  }

  interface IntrinsicElements {
    'svg-clock': SvgClock;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


