/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SvgClock {
    /**
    * Automatically start the clock.
    */
    'autoplay': boolean;
    /**
    * Disable precision. Precision adjusts the rotation of a value (e.g. hours) depending on a lower level value (e.g. minutes).
    */
    'disablePrecision': boolean;
    /**
    * The interval to check the time. Decrease for smoother animation and increased performance cost. Will be ignored if `time` is set.
    */
    'interval': number;
    /**
    * Determine whether the clock is running.
    */
    'isRunning': () => Promise<boolean>;
    /**
    * Define a URL to load the SVG from. Combining this with inline SVG will result in untested behavior.
    */
    'src': string;
    /**
    * Start the animation.
    */
    'start': () => Promise<void>;
    /**
    * Stop the animation.
    */
    'stop': () => Promise<void>;
    /**
    * Set a specific time to display. This will disable the automatic ticking. You can pass either a `Date` object or a string in format `hh:mm:ss`.
    */
    'time': string | Date;
  }
}

declare global {


  interface HTMLSvgClockElement extends Components.SvgClock, HTMLStencilElement {}
  var HTMLSvgClockElement: {
    prototype: HTMLSvgClockElement;
    new (): HTMLSvgClockElement;
  };
  interface HTMLElementTagNameMap {
    'svg-clock': HTMLSvgClockElement;
  }
}

declare namespace LocalJSX {
  interface SvgClock extends JSXBase.HTMLAttributes<HTMLSvgClockElement> {
    /**
    * Automatically start the clock.
    */
    'autoplay'?: boolean;
    /**
    * Disable precision. Precision adjusts the rotation of a value (e.g. hours) depending on a lower level value (e.g. minutes).
    */
    'disablePrecision'?: boolean;
    /**
    * The interval to check the time. Decrease for smoother animation and increased performance cost. Will be ignored if `time` is set.
    */
    'interval'?: number;
    /**
    * Define a URL to load the SVG from. Combining this with inline SVG will result in untested behavior.
    */
    'src'?: string;
    /**
    * Set a specific time to display. This will disable the automatic ticking. You can pass either a `Date` object or a string in format `hh:mm:ss`.
    */
    'time'?: string | Date;
  }

  interface IntrinsicElements {
    'svg-clock': SvgClock;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


